### ISSUE TITLE
Composer can't find version 2.0

### ISSUE THREAD

**Issue by willbocc** [leowebguy/simple-mailchimp#11]
Few issues running `composer update` today

```
  Problem 1
    - Root composer.json requires leowebguy/simple-mailchimp 2.0, found leowebguy/simple-mailchimp[dev-main, 1.0.0, 1.0.1, 1.0.2, 1.0.4] but these do not match your constraint and are therefore not installable. Make sure you either fix the constraint or avoid updating this package to keep the one present in the lock file (leowebguy/simple-mailchimp[2.0.0]).
```

It looks like you've got from version numbers starting at 2, then gone backwards.
All sorted now by using `"leowebguy/simple-mailchimp": "^1.0",` in my composer.json but thought I would raise it if anyone else bumps into the issue.

**Comment by leowebguy** [comment]
you're right! I released a 2.0 version intended to be c4 only, then 1h later I figured there was a solution for releasing a 1.0.4 that's compatible with c3/c4 php 7/8 so I rolled back.
