### ISSUE TITLE
Mailchimp error: Invalid Resource

### ISSUE THREAD

**Issue by baldhadhaval08** [leowebguy/simple-mailchimp#12]
Hello,

I'm getting Mailchimp error: Invalid Resource error. is there anything I'm missing to pass in body?

![image](https://user-images.githubusercontent.com/36040948/187530992-2ab024da-3070-46d5-b023-28e4e993a735.png)
![image](https://user-images.githubusercontent.com/36040948/187531049-c4fe8d48-9d50-4374-8ce9-747619a931b1.png)

**Comment by leowebguy** [comment]
this msg comes from mailchimp api, something wrong with your parameters

```
MC_API_KEY=xxx12345x1234x123xxx123xxxxx123xx-us14
MC_LIST_ID=xxx1234xx1234
```

check readme, https://github.com/leowebguy/simple-mailchimp

**Comment by leowebguy** [comment]
also would be good to pass the name, even if empty
