### ISSUE TITLE
400 Bad request

### ISSUE THREAD

**Issue by outline4** [leowebguy/simple-mailchimp#16]
Hi, 

I get a console error when submitting the code. 

XHR POST https://www.mypage.ch/mailchimp/send
[HTTP/2 400 Bad Request 299ms]

It's the first time I use this plugin, so I hope I didn't make a stupid mistake.

Cheers  
Stefan

**Comment by leowebguy** [comment]
confirm the plugin is active

admin settings plugins

**Comment by outline4** [comment]
Hi, thanks for getting back. 

Yes, the plugin is active: 

<img width="1020" alt="Bildschirmfoto 2023-01-23 um 17 38 02" src="https://user-images.githubusercontent.com/145828/214110183-741c955a-397c-4189-8ec9-81a47ec5d7a8.png">

and when visiting the url https://www.mypage.ch/mailchimp/send it displays this: 

<img width="278" alt="Bildschirmfoto 2023-01-23 um 17 39 25" src="https://user-images.githubusercontent.com/145828/214110421-13d73ad6-9768-4f41-86a2-aea12715fb3c.png">

I also tried to disable devMode, but nothing seem to work. 

I have the following specs: 

PHP version | 8.1.13  
Craft CMS 4.3.6.1  
Simple Mailchimp | 2.0.0

**Comment by leowebguy** [comment]
the endpoint only accept post, you gotta implement some ajax/xhr to get it
going

**Comment by outline4** [comment]
Hi, 

I just looked at the endpoint to see if it is active. 
Of course I took your example code.
It's the ajax request that is generating the error.  

This is the code: 

	<article class="content_block line">
		<form method="post" id="newsletter">
			{{ csrfInput() }}
			<div class="grid">
				<div class="col-1-2"><h2>Newsletter:</h2></div>
				<div class="col-1-2">
					<input type="email" placeholder="Email" name="email">
					<button type="submit">Abbonnieren</button>
				</div>
			</div>
		</form>
	</article>
	
	{% js %}
	
		$(document).ready(function(){
		    $('#newsletter').submit((e) => {
		        e.preventDefault();
		        $.post({
		            url: '/mailchimp/send',
		            data: $(this).serialize(),
		            success: (r) => {
		                if (r.success == true) {
		                    $('form')
		                        .append(`<div class='success'>${r.msg}</div>`)
		                        .hide().fadeIn()
		                        .delay(6000).fadeOut();
	
		                    $(this).trigger("reset");
		                } else {
		                    $('form')
		                        .append(`<div class='error'>${r.msg}</div>`)
		                        .hide().fadeIn()
		                        .delay(6000).fadeOut();
		                }
		            }
		        });
		    });
		});
	
	{% endjs %}

Anything that I could check to get this going?  
Any help appreciated!

**Comment by leowebguy** [comment]
400 could be csrf... check your config/general.php and confirm you have
key/secret in your env and plugin settings

I know the plugin works because I have 300+ active installs and no
complaints so far.

**Comment by outline4** [comment]
Hi, Thanks,

I've checked everything. 

The only thing I can think of at the moment that it is a SOLO licence.  
Do you think that could affect the plugin? 

Cheers  
Stefan

**Comment by leowebguy** [comment]
nope. that doesn't affect

**Comment by leowebguy** [comment]
hey arnold,
did you figure out?

make sure you've followed these steps

add you mailchimp keys into your env file
# Mailchimp
MC_API_KEY=aaa-us14
MC_LIST_ID=bbb
confirm you have {{ csrfInput() }} within your form...

drop this code into a template and try submitting it

<form method="post">
    {{ csrfInput() }}
    <input type="hidden" name="tags" value="group1">
    <input type="text" name="name">
    <input type="email" name="email">
    <button type="submit">Submit</button>
</form>
{% js %}
    (function($) {
        $('form').submit(function(e) {
            e.preventDefault();
            $.post({
                url: '/mailchimp/send',
                data: $(this).serialize(),
                success: (r) => {
                    if (r.success) {
                        alert(r.msg)
                    } else {
                        alert(r.msg)
                    }
                },
                error: (e) => {
                    alert(e)
                }
            });
        });
    })(jQuery);
{% endjs %}

{% js 'https://code.jquery.com/jquery-3.6.0.min.js' %}

**Comment by leowebguy** [comment]
also >> /admin/settings/plugins/simple-mailchimp

confirm you have either the .env or the key and list id itself.

**Comment by timvermaercke** [comment]
I had the same issue.

This was my vanilla js code that did **not** work.

```ts
...
      mailchimpForm.onsubmit = function (e) {
        e.preventDefault();
        const formData = new FormData(this);
        const email = formData.get('email');
        const csrf = formData.get('CRAFT_CSRF_TOKEN');
        const body = { email, CRAFT_CSRF_TOKEN: csrf };

        fetch('/mailchimp/send', {
          method: 'POST',
          body: JSON.stringify(body),
          headers: {
            'Content-Type': 'application/json',
          },
        })
...
```

Turns out the plugin [requires](https://github.com/leowebguy/simple-mailchimp/blob/main/src/controllers/MailchimpController.php#L32) the contents of `$_POST` which is always going to be empty if you submit it like me as JSON.

The Controller requires us to send data as `Content-Type: x-www-form-urlencoded` in order for it to capture the data. So you'll have to change that. Also, `serialize` is a jQuery method, so I had to recreate that.

This is my code that works;

```ts
const Mailchimp = {
  init: () => {
    const mailchimpForm = document.getElementById('mailchimp-form');
    const form = document.getElementById('newsletter-form');

    if (mailchimpForm && form) {
      mailchimpForm.onsubmit = function (e) {
        e.preventDefault();
        const formData = new FormData(this);
        const email = formData.get('email');
        const csrf = formData.get('CRAFT_CSRF_TOKEN');
        const body = { email, CRAFT_CSRF_TOKEN: csrf };

        const serialize = (obj) => {
          var str: string[] = [];
          for (var p in obj)
            if (obj.hasOwnProperty(p)) {
              str.push(encodeURIComponent(p) + '=' + encodeURIComponent(obj[p]));
            }
          return str.join('&');
        };

        fetch('/mailchimp/send', {
          method: 'POST',
          body: serialize(body),
          headers: { 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8' },
        })
          .then((r) => r.json())
          .then((r) => {
            const alert = document.createElement('div');
            alert.classList.add('form-alert');

            if (r.success) {
              alert.innerHTML = 'Success!';
              form?.remove();
            } else {
              alert.classList.add('form-alert--error');
              alert.innerHTML = r.msg;
            }

            mailchimpForm.appendChild(alert);
          })
          .catch((e) => {
            console.error(e);
          });
      };
    }
  },
};

export default Mailchimp;
```
```twig
<form id="mailchimp-form">
    <div class="newsletter-form" id="newsletter-form">
    {{ csrfInput() }}
    <input type="email" placeholder="Your email address" name="email" required/>
    <button type="submit">
        Subscribe
    </button>
    </div>
</form>
```

**Comment by leowebguy** [comment]
nice! good point I'll add vanilla js example to the readme.

**Comment by leowebguy** [comment]
Hey Tim,

You can simplify this a lot ... just do

const mailchimpForm = document.getElementById('mailchimp-form');
mailchimpForm.onsubmit = function (e) {
    e.preventDefault();
    fetch('/mailchimp/send', {
        method: 'POST',
        body: new FormData(this)
    })
    .then((r) => r.json())
    .then((r) => {
        if (r.success) {
            alert(r.msg)
        } else {
            alert(r.msg)
        }
    })
    .catch((e) => {
        console.error(e);
    });
};

**Comment by outline4** [comment]
Hi, 

half a year later on a different site I hit the same 400 Bad request problem.  
This time I had a 402 error, prior to changing jquery from 1.11.1 to 3.3.1

Now it sais:  
Error 400 Bad Request: Unable to verify your data submission.


I'll try the vanilla example and report back.

**Comment by leowebguy** [comment]
Hi,

This is related to CSRF.
Check readme and make sure you added {{ csrfInput() }} to your form.

Leo

**Comment by leowebguy** [comment]
https://github.com/leowebguy/simple-mailchimp/blob/main/README.md#usage

**Comment by outline4** [comment]
This is the exact error: 

<img width="346" alt="Bildschirmfoto 2023-11-22 um 13 16 54" src="https://github.com/leowebguy/simple-mailchimp/assets/145828/9399c6e4-e870-4160-b65e-ca503c19b782">

**Comment by outline4** [comment]
Never mind. 

I took an embedded form and called it a day! 

Thanks anyways

**Comment by outline4** [comment]
> Hi, This is related to CSRF. Check readme and make sure you added {{ csrfInput() }} to your form. Leo
> […](#)

I had csrf in the form. I've even copied it from the original example. 

No worries. It's me, not you ;)
