### ISSUE TITLE
Version 2.0.1 not showing up in Updates or found by composer

### ISSUE THREAD

**Issue by rogerdawkins** [leowebguy/simple-mailchimp#17]
I have version 2.0.0 installed but I would like to install 2.0.1 as I get an error with $_POST which is solved with the 2.0.1 update.

When I run composer update it tells me I'm up to date. If I manually enter 2.0.1 in composer.json but it states that version does not exist.

Is it because you have not updated the version in your composer.json for the plugin?

Roger

**Comment by leowebguy** [comment]
try 2.0.2
