### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by michaelbutler1998** [leowebguy/simple-mailchimp#18]
I keep getting the error "500 internal server error,  ... is not valid JSON when using the plugin both locally and on my server. I have installed the plugin and added my API & list keys as advised in the docs

![image](https://user-images.githubusercontent.com/15836316/223111338-3ca48ff6-e302-4e46-9908-4e7b09ca8c42.png)
![image](https://user-images.githubusercontent.com/15836316/223111485-74753f0e-422c-42cb-8e05-1a8208ce5ce9.png)

<img width="661" alt="image" src="https://user-images.githubusercontent.com/15836316/223111220-91dcd4c1-c256-40e8-9979-198e6ea50556.png">
<img width="475" alt="image" src="https://user-images.githubusercontent.com/15836316/223111247-4c0f419d-c095-41dc-a22b-0691e386071e.png">

**Comment by leowebguy** [comment]
check example provided in the readme ... something with your line 27 up there
