### ISSUE TITLE
Add support for additional post arguments

### ISSUE THREAD

**Issue by jeremyfrank** [leowebguy/simple-mailchimp#19]
I'd like to be able to send additional data, like organization and job title, when users subscribe to a list. Mailchimp lists currently do have these fields, but the plugin looks like it is sending a preconfigured set of fields (email, name, and tags) in the plugin's [service file](https://github.com/leowebguy/simple-mailchimp/blob/main/src/services/MailchimpService.php#L38-L50).

Would you be open to a PR submission with the addition of these additional fields?

**Comment by leowebguy** [comment]
I hear you, but I'd rather keep it simple and consistent with most use cases.
You can always move into a module within your project and modify.

**Comment by brycekirk** [comment]
If you want to do it the wrong way, you can edit `src/services/MailchimpService.php`:
```
$dataMC = [
    'email_address' => $data["email"],
    'status' => 'subscribed',
    'merge_fields' => [
        'MMERGE4' => $data["ROLE"] ?: ''
    ],
];
```
Where `MMERGE4` is the name of the Mailchimp Merge tag (found in Audience > Contacts > Settings > Audience fields and *MERGE* tags) and `$data["ROLE"]` matches the HTML form input `name`.

Updates will obviously break any changes you make in a composer package though. Better to break it out into a custom module.

**Comment by jeremyfrank** [comment]
That's essentially what we ended up needing to do, but in a local copy of the plugin, aliased as a [path repository](https://craftcms.com/docs/4.x/extend/plugin-guide.html#path-repository) in composer.json.

_composer.json_
```json
"repositories": [
  {
    "type": "path",
    "url": "plugins/simple-mailchimp"
  }
],
```

_plugins/simple-mailchimp/src/services/MailchimpService.php_
```php
if (isset($data["organization"])) {
    $dataMC = array_merge_recursive($dataMC, ['merge_fields' => ['ORG' => $data["organization"] ?: '']]);
}

if (isset($data["job_title"])) {
    $dataMC = array_merge_recursive($dataMC, ['merge_fields' => ['TITLE' => $data["job_title"] ?: '']]);
}
```
