### ISSUE TITLE
The new settings screen is required

### ISSUE THREAD

**Issue by michaelcacciatore** [leowebguy/simple-mailchimp#2]
Since 1.0.1, setting the environmental variables only in the `.env` file doesn't work. If you must set the in the `.env` file AND go to the new settings screen and use the environment variables there.

Is this intentional?

**Comment by leowebguy** [comment]
correct.

some devs are not familiar with the .env solo thing.
I'll have those parameters pre-populated by default.

**Comment by leowebguy** [comment]
as next step I want to have [this](https://github.com/leowebguy/simple-mailchimp/blob/main/src/models/MailchimpModel.php#L17) pre-populated with the .env parameters so updates won't break anything.

**Comment by leowebguy** [comment]
since this is a new plugin, I don't think we are going to have lots of issues but...

**Comment by leowebguy** [comment]
fixed
