### ISSUE TITLE
Some example with tags input

### ISSUE THREAD

**Issue by mikolamin** [leowebguy/simple-mailchimp#20]
Could you please provide an example how to use this tag? 

`<input type="hidden" name="tags" value="Tag_1,Tag_2">`

**Comment by leowebguy** [comment]
just add inside the <form> tag

**Comment by mikolamin** [comment]
I have a tag with name "PAGESOURCE" in the Mailchimp. So have to add this name to tags input and how I should to pass the value of input?

`<input type="hidden" name="tags" value="PAGESOURCE">`

**Comment by leowebguy** [comment]
exactly!

**Comment by mikolamin** [comment]
@leowebguy but how the value from the input will send to the Mailchimp? Sorry, I meant "merge_fields".

**Comment by mikolamin** [comment]
Is it possible to support "merge_fields"? 

As an example:

services/MailchimpService.php

      
```
 if (isset($data["tags"])) {
                $dataMC = array_merge($dataMC, ['tags' => explode(',', $data["tags"])]);
            }
```
            
            $vars = $data["vars"];
            if (!empty($vars) && is_array($vars)) {
                $dataMC['merge_fields'] = array_map('strval', $vars);
            }
          
Use it: 
`<input type="hidden" name="vars[NEW_TAG_1]" value="Value of the new tag 1">
<input type="hidden" name="vars[NEW_TAG_2]" value="Value of the new tag 2">`

**Comment by leowebguy** [comment]
check this ... https://github.com/leowebguy/simple-mailchimp/blob/main/src/services/MailchimpService.php#L48
