### ISSUE TITLE
Argument 1 does not implement interface HTMLFormElement.

### ISSUE THREAD

**Issue by wrapper** [leowebguy/simple-mailchimp#21]
Using the example whilst including the # for the ID gives a null error 
`document.getElementById('#mailchimp')`

When I remove the # I get a `Uncaught TypeError: FormData constructor: Argument 1 does not implement interface HTMLFormElement.` error in the console

Seems to relate to [this issue](https://github.com/leowebguy/simple-mailchimp/issues/16#issuecomment-1407353550)

I tried to change ` body: new FormData(form)` to be more specific but then I get the `Mailchimp error: Invalid Resource` error [like this](https://github.com/leowebguy/simple-mailchimp/issues/12)

I would appreciate any guidance here as I am a bit lost!

**Comment by BenHMatrix** [comment]
Get the reference to the form directly with this:
`body: new FormData(e.target)`
