### ISSUE TITLE
How to make this plugin work

### ISSUE THREAD

**Issue by brycekirk** [leowebguy/simple-mailchimp#22]
To make this plugin work, update the Vanilla JS to:
```
const form = document.getElementById('mailchimp')
form.onsubmit = (e) => {
  e.preventDefault();
  fetch('/mailchimp/send', {
    method: 'post',
    body: new FormData(e.target)
  })
  .then((r) => r.json())
  .then((r) => {
    if (r.success) {
      alert(r.msg)
    } else {
      alert(r.msg)
    }
  })
  .catch((e) => {
    console.error(e);
  });
};
```

**Comment by leowebguy** [comment]
I tested the vanilla js and works fine with new FormData(this)
must be some specifics of your app

**Comment by brycekirk** [comment]
`this` may work vs `e.target` , but `const form = document.getElementById('#mailchimp')` from your example (with the `#`) does not work in Chrome–no special app-related stuff.

Thanks for the plugin by the way! was able to edit what you have to bring in custom merge fields as well. Just need to pull the plugin into a custom module.
