### ISSUE TITLE
Double Opt-in - not working

### ISSUE THREAD

**Issue by thomasbendl** [leowebguy/simple-mailchimp#23]
All emails are automatically subscribed to the audience even though I have set up double opt-in in Mailchimp List. I do not receive a double opt-in e-mail. Do you have a fix for this?

**Comment by samuel-clara** [comment]
Same problem here. Is there an option to avoid to apply directly the subscribed status to new emails?

**Comment by leowebguy** [comment]
check 3.0.1 release

https://github.com/leowebguy/simple-mailchimp/blob/main/src/services/MailchimpService.php#L36
https://github.com/leowebguy/simple-mailchimp/blob/main/src/services/MailchimpService.php#L54

**Comment by leowebguy** [comment]
<img width="216" alt="Screenshot 2024-07-24 at 10 09 29 AM" src="https://github.com/user-attachments/assets/3d897e01-a062-456a-bfd9-95abeef8999b">

**Comment by samuel-clara** [comment]
Thank you so much 💛

**Comment by samuel-clara** [comment]
Could you please publish this also for the craft 4 plugin?

**Comment by thomasbendl** [comment]
Thx. for the update 😎 - I also need the craft 4 version please!

**Comment by leowebguy** [comment]
I'll publish later today

**Comment by samuel-clara** [comment]
Please Leo 🙏😊

**Comment by leowebguy** [comment]
try 2.0.3
https://github.com/leowebguy/simple-mailchimp/releases/tag/2.0.3

**Comment by samuel-clara** [comment]
Thank you for the update. I can't update to this version from the terminal nor from the control panel, is it normal?

**Comment by leowebguy** [comment]
on your composer.json you gotta use this

```
"leowebguy/simple-mailchimp": "^2.0",
```

**Comment by samuel-clara** [comment]
When setting 2.03 I get by running composer:
Root composer.json requires leowebguy/simple-mailchimp 2.0.3, found leowebguy/simple-mailchimp[dev-main, 1.0.0, 1.0.1, 1.0.2, 1.0.4, 2.0.0, 2.0.2, 2.0.x-dev, 3.0.0] but it does not match the constraint.

With "leowebguy/simple-mailchimp": "^2.0" it's not updating to 2.03

**Comment by leowebguy** [comment]
it's there... https://github.com/leowebguy/simple-mailchimp/releases

**Comment by leowebguy** [comment]
re-tagged, try again

**Comment by samuel-clara** [comment]
Now it works! Thank you so much

**Comment by robmcfadden** [comment]
Hi! I'm having a similar issue, but with 3.0.1 not installing - Do you need to update the version here as well? https://github.com/leowebguy/simple-mailchimp/blob/3.0.1/composer.json

**Comment by leowebguy** [comment]
allright. try again.

**Comment by robmcfadden** [comment]
That worked, thanks!
