### ISSUE TITLE
"Trying to access array offset on value of type bool" in php > 7.3

### ISSUE THREAD

**Issue by pgworks** [leowebguy/simple-mailchimp#4]
Hi we get "Trying to access array offset on value of type bool" in php > 7.3 in the response of the ajax request. In 7.3 it works!.
Thanks

**Comment by leowebguy** [comment]
tks my friend, it is fixed

```
if (isset($_POST["name"])) {
    $NAME = array_pad(explode(" ", $_POST["name"], 2), 2, null);
    ...
```
