### ISSUE TITLE
Adding merge fields

### ISSUE THREAD

**Issue by AlexandreKilian** [leowebguy/simple-mailchimp#5]
Currently, there is no way to configure merge fields. The only option is to add a combined "name" field, that gets split into first and last name. A cleaner solution, where merge fields can be configured individually (and others besides first and last name could be added) would be great. I could do a fork with a simple solution.

**Comment by leowebguy** [comment]
A simple way of fixing this would be merging these fields with a space in between using JS... PHP would take care of the rest.

```
    $('form.newsletter').submit(function(e) {
        e.preventDefault();
        $.post({
            url: '/mailchimp/send',
            data: {
                name: $('[name=fname]').val() + ' ' + $('[name=lname]').val(),
                email: $('[name=email]').val(),
                CRAFT_CSRF_TOKEN: $('[name=CRAFT_CSRF_TOKEN]]').val()
            },
        ...
```

then

```
    if (isset($_POST["name"])) {
        $name = array_pad(explode(" ", $_POST["name"], 2), 2, null); // if there's a space, it will split into first and last name
        $dataMC = array_merge($dataMC, ['merge_fields' => ['FNAME' => $name[0], 'LNAME' => $name[1] ?: '']]);
    }
```

**Comment by AlexandreKilian** [comment]
yes, thats what I am doing RN, but additional, custom fields can't be handled that way (for example. I often have a field for salutation, company, etc.)

**Comment by samuel-clara** [comment]
Is there a solution for merge fields?

**Comment by leowebguy** [comment]
hey Alex,
please go for it.

thanks!
