### ISSUE TITLE
Direct Access Not Allowed

### ISSUE THREAD

**Issue by mattbloomfield** [leowebguy/simple-mailchimp#6]
So for some reason I'm getting this message back from the mailchimp API. I know it's not on you but I'm curious if you have any idea what could be causing it? 

```{success: false, msg: "Direct access not allowed"}```

**Comment by leowebguy** [comment]
Actually this is from the plugin... you gotta send a POST call, you're probably using GET

```
if ($_POST) {
   ...
}

return ['success' => false, 'msg' => 'Direct access not allowed'];
```

Check this reference https://github.com/leowebguy/simple-mailchimp/blob/main/README.md#usage

**Comment by mattbloomfield** [comment]
Oh what a dumb head I was. Yes, you are correct.

**Comment by mattbloomfield** [comment]
> Oh what a dumb head I was. Yes, you are correct.

Actually, it is sending a post afterall: 

<img width="402" alt="image" src="https://user-images.githubusercontent.com/37582550/164068756-cb300269-8920-41a3-85b4-e65c17e791a2.png">

<img width="736" alt="image" src="https://user-images.githubusercontent.com/37582550/164068843-4595c3ae-ef00-42b1-9d69-eee294a5f025.png">

**Comment by mattbloomfield** [comment]
I'm a little confused because your code seems like it should work. But I logged out more and this is what I see: 

```php
// get what kind of request this is
        $requestType = Craft::$app->request->getMethod();

        return ['success' => false, 'msg' => 'Direct access not allowed', 'type' => $requestType, '$_POST' => $_POST];
```

```
{"success":false,"msg":"Direct access not allowed","type":"POST","$_POST":{"CRAFT_CSRF_TOKEN":"pJhiMPvT2UPR1Kl-RrJofkYUMIZeQp8ZX-5KNFFY_oRBJIskCljx5ZKotk7i9GeMg2VLZSb3rBpHo8m6y6rhTcyrSdhZQ_GzlKHCy67729O2qCyoSEG4f92adwGOfAv7mlXtFLbf8mQvboDKhF1So2RejS-C50tRxxDNmmup01p3O3jSy_efuvAG90HGRYxYZdHPlv4uYYOEigWym8AdC-YgNQlLUcNmM81wEKQCXSMB09QOTMYTbmCYuu6cgSiGlwW14QR8UBXBmyN3l_iPrp7QLKmSKLprepOAo5Oj-8-Y4-WGmB-ReyKKGumqEWO4HT7L-DDYJoe8x10dXOaG1SUF8CI9wkbhqh8ZjF-S-y6RoggedDKaooXGl6BJnwzxIbQxOq38","email":"xxxx.com"}}```

**Comment by mattbloomfield** [comment]
Oh I see the issue. If it doesn't return subscribed then it doesn't hit a return and jumps past the conditional

**Comment by mattbloomfield** [comment]
Changing line 57 to this solves it

```php
                if ($result['status'] == 'subscribed') {
                    return ['success' => true, 'msg' => 'Email subscribed successfully', 'id' => $result['contact_id']];
                } else {
                    return ['success' => false, 'msg' => $result['detail']];
                }
```

**Comment by masiorama** [comment]
@mattbloomfield is this something that you fixed editing src code of the plugin? 
@leowebguy  are you aware of this, do you plans add this fix to your code?
Thanks!

**Comment by leowebguy** [comment]
@mattbloomfield and @masiorama the above is the same as what I have [here](https://github.com/leowebguy/simple-mailchimp/blob/main/src/services/MailchimpService.php#L54), just better logic.
