### ISSUE TITLE
Type of $allowAnonymous must not be defined 

### ISSUE THREAD

**Issue by emilyo-cogapp** [leowebguy/simple-mailchimp#7]
Hello I'm getting this error when I submit a form:
```
yii\base\ErrorException: Type of leowebguy\simplemailchimp\controllers\MailchimpController::$allowAnonymous must not be defined (as in class craft\web\Controller) in /var/www/html/vendor/leowebguy/simple-mailchimp/src/controllers/MailchimpController.php:16
Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
```
Any help appreciated!

**Comment by masiorama** [comment]
Having the same issue.

**Comment by leowebguy** [comment]
hey there!
since this plugin requires `allowAnonymous` had to move C4 into 2.0.0 which is PHP8 compatible
if you're on C3/PHP7.4 make sure you lock "leowebguy/simple-mailchimp": "1.0.2", on your composer json

**Comment by masiorama** [comment]
Thanks. I think this info is important and it could be helpful to document this on package readme.

**Comment by emilyo-cogapp** [comment]
@leowebguy Thanks for the response! I agree with above that it would be great to have a note about this in the README.
