### ISSUE TITLE
PHP 7.4 compatible?

### ISSUE THREAD

**Issue by masiorama** [leowebguy/simple-mailchimp#8]
Hello, I would like to use your plugin on a project which leverages on PHP 7.4.
As I tried to use it I noticed that the first error I get is on MailchimpController, where `protected array|int|bool $allowAnonymous = true;` triggers an error since, AFAIK, is PHP 8 syntax.
Any chance to have this plugin compatible with PHP 7.4?
Thanks in advance.

**Comment by leowebguy** [comment]
hey there!
since this plugin requires `allowAnonymous` had to move c4 into 2.0.0 which is php8 compatible
if you're on 7.4 make sure you tag "leowebguy/simple-mailchimp": "1.0.2", on your composer json

**Comment by masiorama** [comment]
Thanks @leowebguy can you elaborate a bit more about the allowAnonymous thing? Just curious.
