### ISSUE TITLE
$allowAnonymous must not be define

### ISSUE THREAD

**Issue by luketenfour** [leowebguy/simple-mailchimp#9]
PHP Compile Error 'yii\base\ErrorException' with message 'Type of leowebguy\simplemailchimp\controllers\MailchimpController::$allowAnonymous must not be defined (as in class craft\web\Controller)' 

Hi
I get this error when running the plugin. If I go into that file and comment out this line, the plugin works perfectly.
However I'm not sure how to go about overriding this properly.

**Comment by luketenfour** [comment]
Craft CMS 3.7.47.1 PHP 8.1.0
Sorry I didnt see that there was a closed thread already. Although it doesnt seem to help me as yet.

**Comment by leowebguy** [comment]
change your composer.json to 1.0.2 and lock

**Comment by luketenfour** [comment]
Thanks for getting back to me. I did try that but wasn't successful. I've gotten around it by making a copy to edit what I needed but thats obviously no the long term solution.

**Comment by leowebguy** [comment]
fixed
